<Project Sdk="Godot.NET.Sdk/4.5.1">
  <ItemGroup>
    <ProjectReference Include="..\Shapes.Core\Shapes.Core.csproj" />
    <ProjectReference Include="..\Shapes.Ai\Shapes.Ai.csproj" />
    <ProjectReference Include="..\Shapes.Content\Shapes.Content.csproj" />
    <ProjectReference Include="..\Shapes.Godot.Adapter\Shapes.Godot.Adapter.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
</Project>